# Robot.
map_frame_id:                               /odom
robot_base_frame_id:                        /base_link
use_torso_lidar:                            true
sensor_frame_id:                            rgbd_optical_frame #rgbd_optical_frame
sensor_frame_id_torso:                      l515_depth_optical_frame
robot_pose_with_covariance_topic:           /base_link_pose
robot_pose_cache_size:                      200
point_cloud_topic:                          /rgbd/depth/points 
point_cloud_topic_torso:                    /l515/depth/color/points
track_point_frame_id:                       /base_link
track_point_x:                              0.0
track_point_y:                              0.0
track_point_z:                              0.0
min_update_rate:                            2.0
time_tolerance:                             2.0
time_offset_for_point_cloud:                0.0
sensor_processor/ignore_points_above:       1.0
sensor_processor/apply_voxelgrid_filter:    true
sensor_processor/voxelgrid_filter_size:     0.005
robot_motion_map_update/covariance_scale:   0.01

# Map.
length_in_x:                                10.0 
length_in_y:                                10.0 
position_x:                                 0.0 
position_y:                                 0.0 
resolution:                                 0.025
min_variance:                               0.0001
max_variance:                               0.05
mahalanobis_distance_threshold:             2.5
multi_height_noise:                         0.001
surface_normal_positive_axis:               z
fused_map_publishing_rate:                  0.5
enable_visibility_cleanup:                  true
visibility_cleanup_rate:                    1.0
scanning_duration:                          1.0
enable_continuous_cleanup:                  false

# Init submap
initialize_elevation_map:                   true
initialization_method:                      0
length_in_x_init_submap:                    0.55
length_in_y_init_submap:                    0.9
margin_init_submap:                         0.03
init_submap_height_offset:                  0.00
target_frame_init_submap:                   /base_footprint



# PointCloud plane segmentation
plane_distance_threshold:                   0.01
plane_max_iterations:                       1000
plane_cloud_percentage:                     0.9

# PointCloud region growing
region_min_cluster_size:                    2000
region_max_cluster_size:                    10000000
region_neighbours:                          10
region_smoothness_threshold:                2.5
region_curvature_threshold:                 0.5

# Normal calculation method:
# false: normal surface estimation (Best performance)
# true: integral image normal estimation (fast performance)

normal_use_integral:                        false

# Surface normal estimation
normal_nearest_neighbour:                   false
normal_search_radius:                       0.025
normal_k_neighbours:                        101


# Integral Normal Estimation Method:
# 0. COVARIANCE_MATRIX 
# 1. AVERAGE_3D_GRADIENT
# 2. AVERAGE_DEPTH_CHANGE
# 3. SIMPLE_3D_GRADIENT

normal_estimation_method:                   0
normal_max_depth:                           1.0
normal_smoothing_size:                      10.0
